/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/message.proto */

#ifndef PROTOBUF_C_proto_2fmessage_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Pct Pct;


/* --- enums --- */


/* --- messages --- */

struct  _Pct
{
  ProtobufCMessage base;
  float temp_value_c;
  float hum_value;
  float pressure_value;
};
#define PCT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pct__descriptor) \
    , 0, 0, 0 }


/* Pct methods */
void   pct__init
                     (Pct         *message);
size_t pct__get_packed_size
                     (const Pct   *message);
size_t pct__pack
                     (const Pct   *message,
                      uint8_t             *out);
size_t pct__pack_to_buffer
                     (const Pct   *message,
                      ProtobufCBuffer     *buffer);
Pct *
       pct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pct__free_unpacked
                     (Pct *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Pct_Closure)
                 (const Pct *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pct__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fmessage_2eproto__INCLUDED */
